FROM ubuntu@sha256:6f911cac13c27a4f9936b949161f57f1fd27228b821e9912815fa941dc7bec7f 

ARG USERNAME=Mimos
ARG USER_UID=1000
ARG USER_GID=$USER_UID

ENV DEBIAN_FRONTEND=noninteractive

# installing base deps
RUN apt update && \
    apt install --no-install-recommends -y \
    ca-certificates \
    curl \
    build-essential \
    redis-server \
    git \
    ssh \
    sudo \
    cmake \
    python3 \
    python3-pip \
    zlib1g-dev \
    pkg-config \
    libssl-dev

# adding dev user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -ms /bin/bash $USERNAME \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# setting default user
USER $USERNAME



