FROM ubuntu@sha256:42ba2dfce475de1113d55602d40af18415897167d47c2045ec7b6d9746ff148f

ARG USERNAME=Mimos
ARG USER_UID=1000
ARG USER_GID=$USER_UID

ENV DEBIAN_FRONTEND=noninteractive

# installing base deps
RUN apt update && \
    apt install --no-install-recommends -y \
    ca-certificates \
    curl \
    build-essential \
    git \
    ssh \
    sudo \
    python3.10 \
    python3-pip 

# adding dev user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -ms /bin/bash $USERNAME \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# setting default user
USER $USERNAME



